name: tucson-teststand
fqdn: tucson-teststand.lsst.codes
vaultPathPrefix: secret/k8s_operator/tucson-teststand.lsst.codes

applications:
  argo-workflows: true
  exposurelog: true
  narrativelog: true
  nublado: true
  portal: true
  sasquatch: true
  squareone: true
  strimzi: true
  telegraf: true
  telegraf-ds: true
