name: summit
fqdn: summit-lsp.lsst.codes
vaultPathPrefix: secret/k8s_operator/summit-lsp.lsst.codes

applications:
  exposurelog: true
  narrativelog: true
  nublado: true
  portal: true
  postgres: true
  sasquatch: true
  squareone: true
  strimzi: true
  telegraf: true
  telegraf-ds: true
