name: "roundtable-dev"
fqdn: "roundtable-dev.lsst.cloud"
gcp:
  projectId: "roundtable-dev-abe2"
  region: "us-central1"
  clusterName: "roundtable-dev"
onepassword:
  connectUrl: "https://roundtable-dev.lsst.cloud/1password"
  vaultTitle: "RSP roundtable-dev.lsst.cloud"
vaultPathPrefix: "secret/phalanx/roundtable-dev"

applications:
  giftless: true
  kubernetes-replicator: true
  monitoring: true
  onepassword-connect: true
  ook: true
  sasquatch: true
  squarebot: true
  squareone: true
  strimzi: true
  strimzi-access-operator: true
