butlerRepositoryIndex: "s3://rubin-summit-users/data-repos.yaml"
fqdn: usdf-rsp-dev.slac.stanford.edu
name: usdfdev
vaultUrl: "https://vault.slac.stanford.edu"
vaultPathPrefix: secret/rubin/usdf-rsp-dev

applications:
  # This environment uses an ingress managed in a separate Kubernetes cluster,
  # despite that configuration not being officially supported by Phalanx.
  cert-manager: false
  ingress-nginx: false

  alert-stream-broker: true
  datalinker: true
  exposurelog: true
  jira-data-proxy: true
  livetap: true
  mobu: true
  narrativelog: true
  noteburst: true
  nublado: true
  obsloctap: true
  plot-navigator: true
  portal: true
  postgres: true
  rubintv: true
  sasquatch: true
  schedview-prenight: true
  schedview-snapshot: true
  semaphore: true
  siav2: true
  ssotap: true
  squareone: true
  strimzi: true
  tap: true
  times-square: true
