butlerRepositoryIndex: "s3://rubin-summit-users/data-repos.yaml"
fqdn: usdf-rsp.slac.stanford.edu
name: usdfprod
vaultUrl: "https://vault.slac.stanford.edu"
vaultPathPrefix: secret/rubin/usdf-rsp

applications:
  # This environment uses an ingress managed in a separate Kubernetes cluster,
  # despite that configuration not being officially supported by Phalanx.
  cert-manager: false
  ingress-nginx: false

  datalinker: true
  exposurelog: true
  livetap: true
  mobu: true
  narrativelog: true
  nublado: true
  plot-navigator: true
  portal: true
  postgres: true
  sasquatch: true
  semaphore: true
  siav2: true
  ssotap: true
  squareone: true
  strimzi: true
  tap: true
