name: roe
fqdn: rsp.lsst.ac.uk
vaultUrl: "https://vault.lsst.ac.uk"
vaultPathPrefix: secret/k8s_operator/roe

applications:
  mobu: true
  nublado: true
  portal: true
  postgres: true
  squareone: true
  tap: true
