name: base
fqdn: base-lsp.lsst.codes
vaultPathPrefix: secret/k8s_operator/base-lsp.lsst.codes

applications:
  argo-workflows: true
  exposurelog: true
  narrativelog: true
  nublado: true
  portal: true
  rubintv: true
  sasquatch: true
  squareone: true
  strimzi: true
  telegraf: true
  telegraf-ds: true
