apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "obsloctap.fullname" . }}
  labels:
    {{- include "obsloctap.labels" . | nindent 4 }}
spec:
{{- if .Values.config.separateSecrets }}
  path: "{{ .Values.global.vaultSecretsPath }}/obsloctap"
{{- else }}
  path: "{{ .Values.global.vaultSecretsPath }}/butler-secret"
{{- end }}
  type: Opaque
