controller:
  config:
    images:
      source:
        type: "docker"
        registry: "ts-dockerhub.lsst.org"
        repository: "sal-sciplat-lab"
      num_releases: 0
      num_weeklies: 3
      num_dailies: 2
      cycle: 32
      recommended_tag: "recommended_c0032"
    lab:
      extraAnnotations:
        k8s.v1.cni.cncf.io/networks: "kube-system/dds"
      env:
        DAF_BUTLER_REPOSITORY_INDEX: "/project/data-repos.yaml"
        LSST_DDS_INTERFACE: net1
        LSST_DDS_PARTITION_PREFIX: tucson
        LSST_SITE: tucson
        PGPASSFILE: "/opt/lsst/software/jupyterlab/secrets/postgres-credentials.txt"
        PGUSER: "oods"
      initContainers:
        - name: "inithome"
          image:
            repository: "ghcr.io/lsst-sqre/nublado-inithome"
            tag: "4.0.1"
          privileged: true
          volumeMounts:
            - containerPath: "/home"
              volumeName: "home"
      pullSecret: "pull-secret"
      secrets:
        - secretName: "nublado-lab-secret"
          secretKey: "postgres-credentials.txt"
      volumes:
        - name: "home"
          source:
            type: "nfs"
            serverPath: "/jhome"
            server: "nfs-jhome.tu.lsst.org"
        - name: "project"
          source:
            type: "nfs"
            serverPath: "/project"
            server: "nfs-project.tu.lsst.org"
        - name: "scratch"
          source:
            type: "nfs"
            serverPath: "/scratch"
            server: "nfs-scratch.tu.lsst.org"
        - name: "datasets"
          source:
            type: "nfs"
            serverPath: "/lsstdata"
            server: "nfs-lsstdata.tu.lsst.org"
        - name: "latiss"
          source:
            type: "nfs"
            serverPath: "/auxtel/repo/LATISS"
            server: "nfs-auxtel.tu.lsst.org"
        - name: "obs-env"
          source:
            type: "nfs"
            serverPath: "/obs-env"
            server: "nfs-obsenv.tu.lsst.org"
        - name: "lsstcomcan"
          source:
            type: "nfs"
            serverPath: "/repo/LSSTComCam"
            server: "comcam-archiver.tu.lsst.org"
        - name: "auxtel"
          source:
            type: "nfs"
            serverPath: "/auxtel/lsstdata/TTS/auxtel"
            server: "nfs-auxtel.tu.lsst.org"
        - name: "comcam"
          source:
            type: "nfs"
            serverPath: "/lsstdata/TTS/comcam"
            server: "comcam-archiver.tu.lsst.org"
      volumeMounts:
        - containerPath: "/home"
          volumeName: "home"
        - containerPath: "/project"
          volumeName: "project"
        - containerPath: "/scratch"
          volumeName: "scratch"
        - containerPath: "/datasets"
          volumeName: "datasets"
        - containerPath: "/repo/LATISS"
          volumeName: "latiss"
        - containerPath: "/net/obs-env"
          volumeName: "obs-env"
        - containerPath: "/repo/LSSTComCam"
          volumeName: "lsstcomcam"
        - containerPath: "/data/lsstdata/TTS/auxtel"
          volumeName: "auxtel"
        - containerPath: "/data/lsstdata/TTS/comcam"
          volumeName: "comcam"

jupyterhub:
  cull:
    users: false
    removeNamedServers: false
    timeout: 432000
    every: 300
    maxAge: 2160000
  hub:
    db:
      upgrade: true
      url: "postgresql://nublado3@postgresdb01.tu.lsst.org/nublado3"
