apiVersion: v2
name: strimzi
type: application
version: 1.0.0
description: Strimzi Kafka Operator
home: https://strimzi.io
appVersion: "0.26.0"
dependencies:
  - name: strimzi-kafka-operator
    version: "0.38.0"
    repository: https://strimzi.io/charts/
